project:
    type: book
    output-dir: docs
    resources:
        - "My_Personal_Reviews/UTS-5_My_Personal_Reviews.xlsx"
        - "My_Personal_Reviews/UTS-5_My_Personal_Reviews.csv"
        - "My_Personal_Reviews/UTS-5_My_Personal_Reviews.htm"

book:
    title: "Andrew Tedjapratama"
    subtitle: "Portfolio Asesmen II-2100 KIPP"
    author: "13523148 Andrew Tedjapratama"
    date: "10/31/2025"
    chapters:
        - index.qmd
        - All_About_me/index.qmd
        - My_Song_for_You/index.qmd
        - My_Stories_for_You/index.qmd
        - My_Shapes/index.qmd
        - My_Personal_Reviews/index.qmd
        - My_Concepts/index.qmd
        - My_Opinions/index.qmd
        - My_Innovations/index.qmd
        - My_Knowledge/index.qmd
        - My_Professional_Reviews/index.qmd
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
    html:
        theme:
            - cosmo
            - brand
    pdf:
        documentclass: scrreprt
